name: Check New Files
on: pull_request
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@9a6dabf8d15381f97f1c770257a1a0db59c28a47 #v35.4.0

      - name: Auto Comment
        uses: wow-actions/auto-comment@2fc064c21cfb2505de3c5c10e1473b8eb7beca1a #v1.1.2
        if: steps.changed-files.outputs.added_files != 0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: |
            Add new files detected.
